name: MuleSoft Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: maven
      
      - name: Build with Maven
        run: mvn -B package --settings .github/settings.xml
        env: 
          ANYPOINT_PLATFORM_CLIENT_ID: ${{ secrets.CONNECTED_APP_CLIENT_ID }}
          ANYPOINT_PLATFORM_CLIENT_SECRET: ${{ secrets.CONNECTED_APP_CLIENT_SECRET }}