name: MuleSoft Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: maven
      
      - name: Build with Maven
        run: mvn -B package --settings .github/settings.xml
        env: 
          ANYPOINT_PLATFORM_CLIENT_ID: ${{ secrets.CONNECTED_APP_CLIENT_ID }}
          ANYPOINT_PLATFORM_CLIENT_SECRET: ${{ secrets.CONNECTED_APP_CLIENT_SECRET }}
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: mule-application
          path: target/*.jar
          if-no-files-found: error
          retention-days: 5