name: MuleSoft Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: maven
      
      - name: Build with Maven
        run: mvn -B package --settings .github/settings.xml
        env: 
          ANYPOINT_PLATFORM_CLIENT_ID: ${{ vars.CONNECTED_APP_CLIENT_ID }}
          ANYPOINT_PLATFORM_CLIENT_SECRET: ${{ secrets.CONNECTED_APP_CLIENT_SECRET }}
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: mule-application
          path: target/*.jar
          if-no-files-found: error
          retention-days: 5
  deploy:
    name: Deploy to CloudHub 2.0
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: maven
      - name: Deploy to CloudHub 2.0
        run: |
          mvn clean deploy -DmuleDeploy --settings .github/settings.xml \
            -DconnectedApp.clientId="${{ vars.CONNECTED_APP_CLIENT_ID }}" \
            -DconnectedApp.clientSecret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}" \
            -Danypoint.platform.client_id="${{ vars.ANYPOINT_PLATFORM_CLIENT_ID }}" \
            -Danypoint.platform.client_secret="${{ secrets.ANYPOINT_PLATFORM_CLIENT_SECRET }}" \
            -Ddb.password="${{ secrets.DB_PASSWORD }}"
        env: 
          ANYPOINT_PLATFORM_CLIENT_ID: ${{ vars.CONNECTED_APP_CLIENT_ID }}
          ANYPOINT_PLATFORM_CLIENT_SECRET: ${{ secrets.CONNECTED_APP_CLIENT_SECRET }}
